package keyboard

/*
DO NOT EDIT
	This file has been automatically generated by the escSequence tool. Any
	changes made will be lost.
*/

const (
	Key_Ctrl_A KeyPress = -1000 - iota
	Key_Ctrl_B
	Key_Ctrl_C
	Key_Ctrl_D
	Key_Ctrl_E
	Key_Ctrl_F
	Key_Ctrl_G
	Key_Ctrl_H
	Key_Ctrl_I
	Key_Ctrl_J
	Key_Ctrl_K
	Key_Ctrl_L
	Key_Ctrl_M
	Key_Ctrl_N
	Key_Ctrl_O
	Key_Ctrl_P
	Key_Ctrl_Q
	Key_Ctrl_R
	Key_Ctrl_S
	Key_Ctrl_T
	Key_Ctrl_U
	Key_Ctrl_V
	Key_Ctrl_W
	Key_Ctrl_X
	Key_Ctrl_Y
	Key_Ctrl_Z
	Key_Alt_0
	Key_Alt_1
	Key_Alt_2
	Key_Alt_3
	Key_Alt_4
	Key_Alt_5
	Key_Alt_6
	Key_Alt_7
	Key_Alt_8
	Key_Alt_9
	Key_Alt_A
	Key_Alt_B
	Key_Alt_C
	Key_Alt_D
	Key_Alt_E
	Key_Alt_F
	Key_Alt_G
	Key_Alt_H
	Key_Alt_I
	Key_Alt_J
	Key_Alt_K
	Key_Alt_L
	Key_Alt_M
	Key_Alt_N
	Key_Alt_P
	Key_Alt_Q
	Key_Alt_R
	Key_Alt_S
	Key_Alt_T
	Key_Alt_U
	Key_Alt_V
	Key_Alt_W
	Key_Alt_X
	Key_Alt_Y
	Key_Alt_Z
	Key_Alt_a
	Key_Alt_b
	Key_Alt_c
	Key_Alt_d
	Key_Alt_e
	Key_Alt_f
	Key_Alt_g
	Key_Alt_h
	Key_Alt_i
	Key_Alt_j
	Key_Alt_k
	Key_Alt_l
	Key_Alt_m
	Key_Alt_n
	Key_Alt_o
	Key_Alt_p
	Key_Alt_q
	Key_Alt_r
	Key_Alt_s
	Key_Alt_t
	Key_Alt_u
	Key_Alt_v
	Key_Alt_w
	Key_Alt_x
	Key_Alt_y
	Key_Alt_z
	Key_Delete
	Key_Down
	Key_End
	Key_F1
	Key_F10
	Key_F11
	Key_F12
	Key_F2
	Key_F3
	Key_F4
	Key_F5
	Key_F6
	Key_F7
	Key_F8
	Key_F9
	Key_Home
	Key_Insert
	Key_Left
	Key_PgDown
	Key_PgUp
	Key_Right
	Key_Shift_Delete
	Key_Shift_Enter
	Key_Shift_F1
	Key_Shift_F10
	Key_Shift_F11
	Key_Shift_F12
	Key_Shift_F2
	Key_Shift_F3
	Key_Shift_F4
	Key_Shift_F5
	Key_Shift_F6
	Key_Shift_F7
	Key_Shift_F8
	Key_Shift_F9
	Key_Up
)

var KeyNames = map[KeyPress]string{
	Key_Escape:       "Escape",
	Key_Enter:        "Enter",
	Key_Backspace:    "Backspace",
	Key_Ctrl_A:       "Ctrl_A",
	Key_Ctrl_B:       "Ctrl_B",
	Key_Ctrl_C:       "Ctrl_C",
	Key_Ctrl_D:       "Ctrl_D",
	Key_Ctrl_E:       "Ctrl_E",
	Key_Ctrl_F:       "Ctrl_F",
	Key_Ctrl_G:       "Ctrl_G",
	Key_Ctrl_H:       "Ctrl_H",
	Key_Ctrl_I:       "Ctrl_I",
	Key_Ctrl_J:       "Ctrl_J",
	Key_Ctrl_K:       "Ctrl_K",
	Key_Ctrl_L:       "Ctrl_L",
	Key_Ctrl_M:       "Ctrl_M",
	Key_Ctrl_N:       "Ctrl_N",
	Key_Ctrl_O:       "Ctrl_O",
	Key_Ctrl_P:       "Ctrl_P",
	Key_Ctrl_Q:       "Ctrl_Q",
	Key_Ctrl_R:       "Ctrl_R",
	Key_Ctrl_S:       "Ctrl_S",
	Key_Ctrl_T:       "Ctrl_T",
	Key_Ctrl_U:       "Ctrl_U",
	Key_Ctrl_V:       "Ctrl_V",
	Key_Ctrl_W:       "Ctrl_W",
	Key_Ctrl_X:       "Ctrl_X",
	Key_Ctrl_Y:       "Ctrl_Y",
	Key_Ctrl_Z:       "Ctrl_Z",
	Key_Alt_0:        "Alt_0",
	Key_Alt_1:        "Alt_1",
	Key_Alt_2:        "Alt_2",
	Key_Alt_3:        "Alt_3",
	Key_Alt_4:        "Alt_4",
	Key_Alt_5:        "Alt_5",
	Key_Alt_6:        "Alt_6",
	Key_Alt_7:        "Alt_7",
	Key_Alt_8:        "Alt_8",
	Key_Alt_9:        "Alt_9",
	Key_Alt_A:        "Alt_A",
	Key_Alt_B:        "Alt_B",
	Key_Alt_C:        "Alt_C",
	Key_Alt_D:        "Alt_D",
	Key_Alt_E:        "Alt_E",
	Key_Alt_F:        "Alt_F",
	Key_Alt_G:        "Alt_G",
	Key_Alt_H:        "Alt_H",
	Key_Alt_I:        "Alt_I",
	Key_Alt_J:        "Alt_J",
	Key_Alt_K:        "Alt_K",
	Key_Alt_L:        "Alt_L",
	Key_Alt_M:        "Alt_M",
	Key_Alt_N:        "Alt_N",
	Key_Alt_P:        "Alt_P",
	Key_Alt_Q:        "Alt_Q",
	Key_Alt_R:        "Alt_R",
	Key_Alt_S:        "Alt_S",
	Key_Alt_T:        "Alt_T",
	Key_Alt_U:        "Alt_U",
	Key_Alt_V:        "Alt_V",
	Key_Alt_W:        "Alt_W",
	Key_Alt_X:        "Alt_X",
	Key_Alt_Y:        "Alt_Y",
	Key_Alt_Z:        "Alt_Z",
	Key_Alt_a:        "Alt_a",
	Key_Alt_b:        "Alt_b",
	Key_Alt_c:        "Alt_c",
	Key_Alt_d:        "Alt_d",
	Key_Alt_e:        "Alt_e",
	Key_Alt_f:        "Alt_f",
	Key_Alt_g:        "Alt_g",
	Key_Alt_h:        "Alt_h",
	Key_Alt_i:        "Alt_i",
	Key_Alt_j:        "Alt_j",
	Key_Alt_k:        "Alt_k",
	Key_Alt_l:        "Alt_l",
	Key_Alt_m:        "Alt_m",
	Key_Alt_n:        "Alt_n",
	Key_Alt_o:        "Alt_o",
	Key_Alt_p:        "Alt_p",
	Key_Alt_q:        "Alt_q",
	Key_Alt_r:        "Alt_r",
	Key_Alt_s:        "Alt_s",
	Key_Alt_t:        "Alt_t",
	Key_Alt_u:        "Alt_u",
	Key_Alt_v:        "Alt_v",
	Key_Alt_w:        "Alt_w",
	Key_Alt_x:        "Alt_x",
	Key_Alt_y:        "Alt_y",
	Key_Alt_z:        "Alt_z",
	Key_Delete:       "Delete",
	Key_Down:         "Down",
	Key_End:          "End",
	Key_F1:           "F1",
	Key_F10:          "F10",
	Key_F11:          "F11",
	Key_F12:          "F12",
	Key_F2:           "F2",
	Key_F3:           "F3",
	Key_F4:           "F4",
	Key_F5:           "F5",
	Key_F6:           "F6",
	Key_F7:           "F7",
	Key_F8:           "F8",
	Key_F9:           "F9",
	Key_Home:         "Home",
	Key_Insert:       "Insert",
	Key_Left:         "Left",
	Key_PgDown:       "PgDown",
	Key_PgUp:         "PgUp",
	Key_Right:        "Right",
	Key_Shift_Delete: "Shift_Delete",
	Key_Shift_Enter:  "Shift_Enter",
	Key_Shift_F1:     "Shift_F1",
	Key_Shift_F10:    "Shift_F10",
	Key_Shift_F11:    "Shift_F11",
	Key_Shift_F12:    "Shift_F12",
	Key_Shift_F2:     "Shift_F2",
	Key_Shift_F3:     "Shift_F3",
	Key_Shift_F4:     "Shift_F4",
	Key_Shift_F5:     "Shift_F5",
	Key_Shift_F6:     "Shift_F6",
	Key_Shift_F7:     "Shift_F7",
	Key_Shift_F8:     "Shift_F8",
	Key_Shift_F9:     "Shift_F9",
	Key_Up:           "Up",
}

var seqMap = &tree{
	c: map[uint8]*tree{
		'0': &tree{
			kp: Key_Alt_0,
		},
		'1': &tree{
			kp: Key_Alt_1,
		},
		'2': &tree{
			kp: Key_Alt_2,
		},
		'3': &tree{
			kp: Key_Alt_3,
		},
		'4': &tree{
			kp: Key_Alt_4,
		},
		'5': &tree{
			kp: Key_Alt_5,
		},
		'6': &tree{
			kp: Key_Alt_6,
		},
		'7': &tree{
			kp: Key_Alt_7,
		},
		'8': &tree{
			kp: Key_Alt_8,
		},
		'9': &tree{
			kp: Key_Alt_9,
		},
		'A': &tree{
			kp: Key_Alt_A,
		},
		'B': &tree{
			kp: Key_Alt_B,
		},
		'C': &tree{
			kp: Key_Alt_C,
		},
		'D': &tree{
			kp: Key_Alt_D,
		},
		'E': &tree{
			kp: Key_Alt_E,
		},
		'F': &tree{
			kp: Key_Alt_F,
		},
		'G': &tree{
			kp: Key_Alt_G,
		},
		'H': &tree{
			kp: Key_Alt_H,
		},
		'I': &tree{
			kp: Key_Alt_I,
		},
		'J': &tree{
			kp: Key_Alt_J,
		},
		'K': &tree{
			kp: Key_Alt_K,
		},
		'L': &tree{
			kp: Key_Alt_L,
		},
		'M': &tree{
			kp: Key_Alt_M,
		},
		'N': &tree{
			kp: Key_Alt_N,
		},
		'O': &tree{
			c: map[uint8]*tree{
				'2': &tree{
					c: map[uint8]*tree{
						'P': &tree{
							kp: Key_Shift_F1,
						},
						'Q': &tree{
							kp: Key_Shift_F2,
						},
						'R': &tree{
							kp: Key_Shift_F3,
						},
						'S': &tree{
							kp: Key_Shift_F4,
						},
					},
				},
				'M': &tree{
					kp: Key_Shift_Enter,
				},
				'P': &tree{
					kp: Key_F1,
				},
				'Q': &tree{
					kp: Key_F2,
				},
				'R': &tree{
					kp: Key_F3,
				},
				'S': &tree{
					kp: Key_F4,
				},
			},
		},
		'P': &tree{
			kp: Key_Alt_P,
		},
		'Q': &tree{
			kp: Key_Alt_Q,
		},
		'R': &tree{
			kp: Key_Alt_R,
		},
		'S': &tree{
			kp: Key_Alt_S,
		},
		'T': &tree{
			kp: Key_Alt_T,
		},
		'U': &tree{
			kp: Key_Alt_U,
		},
		'V': &tree{
			kp: Key_Alt_V,
		},
		'W': &tree{
			kp: Key_Alt_W,
		},
		'X': &tree{
			kp: Key_Alt_X,
		},
		'Y': &tree{
			kp: Key_Alt_Y,
		},
		'Z': &tree{
			kp: Key_Alt_Z,
		},
		'[': &tree{
			c: map[uint8]*tree{
				'1': &tree{
					c: map[uint8]*tree{
						'5': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F5,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F5,
								},
							},
						},
						'7': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F6,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F6,
								},
							},
						},
						'8': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F7,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F7,
								},
							},
						},
						'9': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F8,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F8,
								},
							},
						},
					},
				},
				'2': &tree{
					c: map[uint8]*tree{
						'0': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F9,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F9,
								},
							},
						},
						'1': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F10,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F10,
								},
							},
						},
						'3': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F11,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F11,
								},
							},
						},
						'4': &tree{
							c: map[uint8]*tree{
								';': &tree{
									c: map[uint8]*tree{
										'2': &tree{
											c: map[uint8]*tree{
												'~': &tree{
													kp: Key_Shift_F12,
												},
											},
										},
									},
								},
								'~': &tree{
									kp: Key_F12,
								},
							},
						},
						'~': &tree{
							kp: Key_Insert,
						},
					},
				},
				'3': &tree{
					c: map[uint8]*tree{
						';': &tree{
							c: map[uint8]*tree{
								'2': &tree{
									c: map[uint8]*tree{
										'~': &tree{
											kp: Key_Shift_Delete,
										},
									},
								},
							},
						},
						'~': &tree{
							kp: Key_Delete,
						},
					},
				},
				'5': &tree{
					c: map[uint8]*tree{
						'~': &tree{
							kp: Key_PgUp,
						},
					},
				},
				'6': &tree{
					c: map[uint8]*tree{
						'~': &tree{
							kp: Key_PgDown,
						},
					},
				},
				'A': &tree{
					kp: Key_Up,
				},
				'B': &tree{
					kp: Key_Down,
				},
				'C': &tree{
					kp: Key_Right,
				},
				'D': &tree{
					kp: Key_Left,
				},
				'F': &tree{
					kp: Key_End,
				},
				'H': &tree{
					kp: Key_Home,
				},
			},
		},
		'a': &tree{
			kp: Key_Alt_a,
		},
		'b': &tree{
			kp: Key_Alt_b,
		},
		'c': &tree{
			kp: Key_Alt_c,
		},
		'd': &tree{
			kp: Key_Alt_d,
		},
		'e': &tree{
			kp: Key_Alt_e,
		},
		'f': &tree{
			kp: Key_Alt_f,
		},
		'g': &tree{
			kp: Key_Alt_g,
		},
		'h': &tree{
			kp: Key_Alt_h,
		},
		'i': &tree{
			kp: Key_Alt_i,
		},
		'j': &tree{
			kp: Key_Alt_j,
		},
		'k': &tree{
			kp: Key_Alt_k,
		},
		'l': &tree{
			kp: Key_Alt_l,
		},
		'm': &tree{
			kp: Key_Alt_m,
		},
		'n': &tree{
			kp: Key_Alt_n,
		},
		'o': &tree{
			kp: Key_Alt_o,
		},
		'p': &tree{
			kp: Key_Alt_p,
		},
		'q': &tree{
			kp: Key_Alt_q,
		},
		'r': &tree{
			kp: Key_Alt_r,
		},
		's': &tree{
			kp: Key_Alt_s,
		},
		't': &tree{
			kp: Key_Alt_t,
		},
		'u': &tree{
			kp: Key_Alt_u,
		},
		'v': &tree{
			kp: Key_Alt_v,
		},
		'w': &tree{
			kp: Key_Alt_w,
		},
		'x': &tree{
			kp: Key_Alt_x,
		},
		'y': &tree{
			kp: Key_Alt_y,
		},
		'z': &tree{
			kp: Key_Alt_z,
		},
	},
}
